apiVersion: v1
kind: Service
metadata:
  name:  myserver
spec:
  type: NodePort 
  selector:
    app: myserver
  ports:
  - port: 1235 
    nodePort: 1235 
    name: http



apiVersion: v1
kind: Service
metadata:
  name:  myserver 
spec:
  selector:
    app: myserver 
  type: ClusterIP
  ports:
    - name: grpclb 
      port: 9090 
      targetPort: 9090 
